#!/bin/bash

#SBATCH --job-name=AhnCNN_OneStop_RC-array
#SBATCH --output=logs/AhnCNN_OneStop_RC-%A_%a.out
#SBATCH --error=logs/AhnCNN_OneStop_RC-%A_%a.err
#SBATCH --partition=work,mig
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --gpus=1
#SBATCH --qos=normal
#SBATCH --cpus-per-task=10
#SBATCH --mem=75G
#SBATCH --array=0-9
#SBATCH --mail-type=ALL
#SBATCH --mail-user=shubi@campus.technion.ac.il

sweep_ids=(ycgeur8r ec0a82in ph9woe9q nsw15ek5 wt1g0zr9 649arr52 esb09qrz b2lt7rji tzcsu863 a8zodc36)
SWEEP_ID=${sweep_ids[$SLURM_ARRAY_TASK_ID]}


srun --overlap --ntasks=1 --nodes=1 --cpus-per-task=$SLURM_CPUS_PER_TASK -p work,mig \
    --container-image=/rg/berzak_prj/shubi/prj/rev05_pytorchlightning+pytorch_lightning.sqsh \
    --container-mounts="/rg/berzak_prj/shubi:/home/shubi" \
    --container-workdir=/home/shubi/eyebench_private \
    bash -c "
echo 'Starting job on $(date)'
source /home/shubi/prj/nvidia_pytorch_25_03_py3_mamba_wrapper.sh
conda activate eyebench
wandb agent EyeRead/OneStop_RC_20251104/$SWEEP_ID"
    
